name: sentiment_pipeline
version: '1.0.0'
config-version: 2

profile: sentiment_pipeline

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  sentiment_pipeline:
    silver:
      +materialized: view
      +schema: silver
    gold:
      +materialized: table
      +schema: gold
